"""empty message

Revision ID: 20ebd548a08e
Revises: None
Create Date: 2014-11-25 17:00:38.083567

"""

# revision identifiers, used by Alembic.
revision = '20ebd548a08e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(u'posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'posts', schema=None) as batch_op:
        batch_op.drop_column('author_id')

    op.drop_table('users')
    ### end Alembic commands ###
